Fix license
test_make (tests.TestMakefile.MakefileTestCase.test_make) ... Traceback (most recent call last):
  File "/home/runner/work/bleachbit/bleachbit/setup.py", line 95, in <module>
    run_setup()
    ~~~~~~~~~^^
  File "/home/runner/work/bleachbit/bleachbit/setup.py", line 57, in run_setup
    setup(name='bleachbit',
    ~~~~~^^^^^^^^^^^^^^^^^^
          version=bleachbit.APP_VERSION,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<17 lines>...
          packages=['bleachbit', 'bleachbit.markovify'],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          **args)
          ^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/setuptools/__init__.py", line 115, in setup
    return distutils.core.setup(**attrs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 160, in setup
    dist.parse_config_files()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/setuptools/dist.py", line 759, in parse_config_files
    self._finalize_license_expression()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/setuptools/dist.py", line 437, in _finalize_license_expression
    SetuptoolsDeprecationWarning.emit(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        "License classifiers are deprecated.",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        #       packages in the ecosystem and cause problems...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/setuptools/warnings.py", line 52, in emit
    warnings.warn(text, cls, stacklevel=stacklevel + 1)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
setuptools.warnings.SetuptoolsDeprecationWarning: License classifiers are deprecated.
!!

        ********************************************************************************
        Please consider removing the following classifiers in favor of a SPDX license expression:

        License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************

!!
ERROR

======================================================================
ERROR: test_make (tests.TestMakefile.MakefileTestCase.test_make)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/bleachbit/bleachbit/tests/TestMakefile.py", line 77, in test_make
    subprocess.check_call(sdist_cmd)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.13.5/x64/bin/python3', 'setup.py', 'sdist']' returned non-zero exit status 1.