Set a 20-second timeout for checking for updates (Python 2.6+)
======================================================================
ERROR: Unit tests for class UpdateCheck
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/az0/bleachbit/tests/TestUpdate.py", line 82, in test_UpdateCheck
    for update in check_updates(True, False, None, None):
  File "./bleachbit/Update.py", line 152, in check_updates
    handle = opener.open(Common.update_check_url)
  File "/opt/python/2.6.9/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/opt/python/2.6.9/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/opt/python/2.6.9/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/opt/python/2.6.9/lib/python2.6/urllib2.py", line 1181, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/opt/python/2.6.9/lib/python2.6/urllib2.py", line 1156, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>