Fix recent commits and improve tests
TypeError: wipe_write() takes no arguments (1 given)
https://travis-ci.org/bleachbit/bleachbit/builds/192048365#L2313

AssertionError: Path still exists '/tmp/bleachbit-test-workerxHciM0'
https://travis-ci.org/bleachbit/bleachbit/builds/192048365#L2372

in TestsCLI
AssertionError: Return code = 1, stderr='no default locale found.
Assuming 'C'

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in
position 31: ordinal not in range(128)