Update URL causing error in test
======================================================================
ERROR: test_update_winapp2 (tests.TestUpdate.UpdateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestUpdate.py", line 129, in test_update_winapp2
    "notahash", print, expect_failure)
  File "c:\python34\lib\unittest\case.py", line 707, in assertRaises
    return context.handle('assertRaises', callableObj, args, kwargs)
  File "c:\python34\lib\unittest\case.py", line 162, in handle
    callable_obj(*args, **kwargs)
  File "C:\projects\bleachbit\bleachbit\Update.py", line 59, in update_winapp2
    doc = opener.open(fullurl=url, timeout=20).read()
  File "c:\python34\lib\urllib\request.py", line 470, in open
    response = meth(req, response)
  File "c:\python34\lib\urllib\request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python34\lib\urllib\request.py", line 502, in error
    result = self._call_chain(*args)
  File "c:\python34\lib\urllib\request.py", line 442, in _call_chain
    result = func(*args)
  File "c:\python34\lib\urllib\request.py", line 685, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\python34\lib\urllib\request.py", line 470, in open
    response = meth(req, response)
  File "c:\python34\lib\urllib\request.py", line 580, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python34\lib\urllib\request.py", line 508, in error
    return self._call_chain(*args)
  File "c:\python34\lib\urllib\request.py", line 442, in _call_chain
    result = func(*args)
  File "c:\python34\lib\urllib\request.py", line 588, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

https://ci.appveyor.com/project/az0/bleachbit/builds/41629329#L2282