Fix change to unit test
=====================================================================
FAIL: test_whitelist (tests.TestCleaner.CleanerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestCleaner.py", line 229, in test_whitelist
    backends['system'].whitelisted(test[0]), test[1], test[0])
AssertionError: C:\Users\appveyor/.cache/obexd