Add workaround for psutil ImportError
- Remove POSIX code from guess_overwrite_paths()
- Remove POSIX-specific code paths because BleachBit 4.6.x
  is for Windows only
- Handle multiple exceptions in guess_overwrite_paths()

Error seen on BleachBit startup on Windows XP3

Traceback (most recent call last):
  File "bleachbit_console.py", line 56, in <module>
  File "bleachbit\__init__.pyo", line 302, in <module>
  File "bleachbit\Windows.pyo", line 41, in <module>
  File "bleachbit\Command.pyo", line 30, in <module>
  File "bleachbit\FileUtilities.pyo", line 44, in <module>
  File "psutil\__init__.pyo", line 142, in <module>
  File "psutil\_pswindows.pyo", line 17, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: A dynamic link library (DLL) initialization routine failed.)
'C:\\Program Files\\BleachBit\\psutil._psutil_windows.pyd'