Fix crash when starting portable application
Traceback (most recent call last): File "bleachbit.py", line 40, in <module>
zlib.error: Error -3 while decompressing data: too many length or distance symbols

Reported by ediowar
Closes https://github.com/bleachbit/bleachbit/issues/704

I reproduced the problem with build 3.0.1.1370 but not with 3.0.1.1369.
Build 70 was commit b52d981338f0943dd51d74693ed626ee5cebec25, so I reversed
that commit.

To reproduce the issue, I used Windows 10's built-in unzip function. Windows
did complain of errors, but apparently the files were corrupt.