Include svg in manifest
Fixes recent commit a5e1524b9f1bf71fff6d3771f6dc56180efc0e68

======================================================================
ERROR: test_make (tests.TestMakefile.MakefileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/bleachbit/bleachbit/tests/TestMakefile.py", line 96, in test_make
    subprocess.check_call(install_command, cwd=extract_subdir)
  File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'install', 'DESTDIR=/tmp/tmpjijjt4fmbleachbit-makefile/install']' returned non-zero exit status 2.