Fix syntax error added in recent commit
It caused many test failures such as

RROR: test_GUI (tests.TestGUI.GUITestCase.test_GUI)
Unit test for class GUI
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestGUI.py", line 191, in test_GUI
    gui.update_progress_bar(0.0)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_progress_bar'
======================================================================
ERROR: test_append_text (tests.TestGUI.GUITestCase.test_append_text)