Fix new traceback when starting on Linux
Traceback (most recent call last):
  File "/bleachbit/bleachbit/GUI.py", line 1096, in on_show
    if Windows.splash_thread.is_alive():
NameError: name 'Windows' is not defined

Introduced in e15dfc651