Fix TypeError in tests/TestMemory.py
Follow up to recent commit bbf25926a00

FAILED tests/TestMemory.py::MemoryTestCase::test_enable_swap_linux -
TypeError: 'unittest.mock.Mock' object does not support the context
manager protocol (missed __exit__ method)