Fix: TypeError when making chaff
The error was trigger when making chaff with stop mode
set to size (e.g., 10MB).

This feature was not available in BleachBit 5.0.2,
so the bug did not affect any stable releases.

Exception in thread Thread-4 (make_files_thread):
Traceback (most recent call last):
File "/usr/lib/python3.13/threading.py", line 1043, in
_bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/bleachbit/bleachbit/GuiChaff.py", line 155, in
make_files_thread
    generated_file_names = generate_2600(
        file_count, output_folder, on_progress=progress_cb,
        should_stop=should_stop)
  File "/bleachbit/bleachbit/Chaff.py", line 259, in generate_2600
    on_progress(1.0 * i / file_count,
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
                generated_file_names=generated_file_names,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                cumulative_size=cumulative_size)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _make_progress_cb.<locals>.progress_cb() got an unexpected
keyword argument 'generated_file_names'. Did you mean
'_generated_file_names'?