Fix error cleaning OpenOffice.org on Windows
After recent changes, BB on Windows requires paths to be normalized.

LP#1454031

Symptom of bug
getsize(C:\Users\username\AppData\Roaming\OpenOffice.org\3\user/registry/cache/org.openoffice.FirstStartWizard.dat)
Traceback (most recent call last):
  File "bleachbit\Cleaner.pyo", line 93, in auto_hide
  File "bleachbit\Command.pyo", line 74, in execute
  File "bleachbit\FileUtilities.pyo", line 362, in getsize
error: (123, 'FindFirstFileW', 'The filename, directory name, or volume label syntax is incorrect.')