Fix another TOCTOU in test_get_commands
This builds on top of recent commit 34ab932

- Allow vanishing based also on %temp% path
- Avoid writing SQLite3 journal file

Fixes this error

FAILED tests/TestCleaner.py::CleanerTestCase::test_get_commands
- AssertionError: The file
C:\Users\RUNNER~1\AppData\Local\Temp\FileUtilitiesTestCase5k7ur4er\bleachbit.tmp.sqlite3-journal
should exist, but it does not.