Fix failing unit test for journald_clean
A few days ago Travis updated the environment from Trusty to Xenial

======================================================================
ERROR: test_journald_clean (tests.TestUnix.UnixTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bleachbit/bleachbit/tests/common.py", line 152, in wrapper
    return f(*args, **kwargs)
  File "/home/travis/build/bleachbit/bleachbit/tests/TestUnix.py", line 115, in test_journald_clean
    journald_clean()
  File "/home/travis/build/bleachbit/bleachbit/bleachbit/Unix.py", line 595, in journald_clean
    raise RuntimeError("Error calling '%s':\n%s" % (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'journalctl --vacuum-size=1':
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.