Troubleshoot error
2026-01-18 00:59:07 - ERROR - upx: dist\python3.dll: NotCompressibleException
upx: dist\vcruntime140.dll: CantPackException: CFGuard enabled PE files are not supported (use --force to disable)
2026-01-18 00:59:07 - INFO - Checking bleachbit_console.exe starts
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\projects\bleachbit\windows\setup.py", line 897, in <module>
    main()
  File "C:\projects\bleachbit\windows\setup.py", line 883, in main
    shrink(fast_build)
  File "C:\projects\bleachbit\windows\setup.py", line 800, in shrink
    upx(fast_build)
  File "C:\projects\bleachbit\windows\setup.py", line 239, in wrapper
    func(*args, **kwargs)
  File "C:\projects\bleachbit\windows\setup.py", line 737, in upx
    assert_execute_console()
  File "C:\projects\bleachbit\windows\setup.py", line 155, in assert_execute_console
    assert_execute([r'dist\bleachbit_console.exe', '--gui', '--exit', '--no-uac'],
  File "C:\projects\bleachbit\windows\setup.py", line 146, in assert_execute
    actual_output = subprocess.check_output(args).decode(SetupEncoding)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\projects\bleachbit\vcpkg_installed\x86-windows\tools\python3\Lib\subprocess.py", line 468, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\projects\bleachbit\vcpkg_installed\x86-windows\tools\python3\Lib\subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dist\\bleachbit_console.exe', '--gui', '--exit', '--no-uac']' returned non-zero exit status 3221225477.
Submodules that appear to be missing, but could also be global names in the parent package: