Add hotfix for failing clipboard test
Saw the following error when using args '['/opt/hostedtoolcache/Python/3.13.3/x64/bin/python3', '-m', 'bleachbit.CLI', '--preview', 'system.clipboard']':
 Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

(CLI.py:5250): Gdk-CRITICAL **: 03:24:32.505: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
no default locale found.  Assuming 'C'
Exception while running operation 'system': 'Unknown option 'clipboard''
Traceback (most recent call last):
  File "/home/runner/work/bleachbit/bleachbit/bleachbit/Worker.py", line 361, in run_operations
    for _dummy in self.clean_operation(operation):
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/runner/work/bleachbit/bleachbit/bleachbit/Worker.py", line 194, in clean_operation
    for (path, search) in backends[operation].get_deep_scan(option_id):
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/runner/work/bleachbit/bleachbit/bleachbit/Cleaner.py", line 122, in get_deep_scan
    raise RuntimeError(f"Unknown option '{option_id}'")
RuntimeError: Unknown option 'clipboard'

https://github.com/bleachbit/bleachbit/actions/runs/14873970694/job/41768954126