Fix recent regression
This fixes commit 2c9a449ab83fd9404e9f7fe19fa9109b7064d10f
which caused unit test to fail

======================================================================
ERROR: test_purge (tests.TestOptions.OptionsTestCase)
Test purging
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python34\lib\configparser.py", line 761, in get
    value = d[option]
  File "c:\python34\lib\collections\__init__.py", line 805, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "c:\python34\lib\collections\__init__.py", line 797, in __missing__
    raise KeyError(key)
KeyError: 'c\\Users\\appveyor\\AppData\\Local\\Temp\\1\\optionstestcaseq8_lbawa\\foo.xml'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestOptions.py", line 152, in test_purge
    self.assertEqual(myhash, o2.get_hashpath(pathname))
  File "C:\projects\bleachbit\bleachbit\Options.py", line 170, in get_hashpath
    return self.get(path_to_option(pathname), 'hashpath')
  File "C:\projects\bleachbit\bleachbit\Options.py", line 166, in get
    return self.config.get(section, option)
  File "c:\python34\lib\configparser.py", line 764, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'c\\Users\\appveyor\\AppData\\Local\\Temp\\1\\optionstestcaseq8_lbawa\\foo.xml' in section: 'hashpath'
----------------------------------------------------------------------
Ran 222 tests in 140.136s