Check exit code after pip install PyGObject
Because of non-reproducible error seen on AppVeyor CI

pip install pygobject-3.55.0-cp312-cp312-win32.whl...
Processing .\pygobject-3.55.0-cp312-cp312-win32.whl
INFO: pip is looking at multiple versions of pygobject to determine
which version is compatible with other requirements. This could take a
while.
pip3.exe : ERROR: Could not find a version that satisfies the
requirement pycairo>=1.16 (from pygobject) (from versions: none)
At C:\projects\bleachbit\windows\python-gtk3-install.ps1:186 char:1
+ & "$python_home\Scripts\pip3.exe" install $PYGOBJECT_FN
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (ERROR: Could no...versions:
none):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

ERROR: No matching distribution found for pycairo>=1.16