Improve Windows clipboard file path handling and tests
- Query Win32 CF_HDROP before GTK target checks to avoid race condition
- Remove FileNameW fallback in favor of native Win32 clipboard paths
- Use PowerShell Set-Clipboard in tests instead of manual CF_HDROP
construction.
- Improve logging in tests
- Change magic numbers to module-level constants

This change fixes the intermittant error below seen on AppVeyor CI

FAIL: test_get_clipboard_paths_windows
(tests.TestGuiUtil.GUIUtilClipboardTestCase.
  test_get_clipboard_paths_windows)
Get FileNameW paths from the clipboard on Windows.
----------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\bleachbit\tests\TestGuiUtil.py", line 123, in
test_get_clipboard_paths_windows
    self.assertEqual(get1, get2)
AssertionError: Lists differ: [] !=
['C:\\Users\\appveyor\\...\\clipboard-path-2']