Fix: `Got unknown status from AppVeyor API: starting`
In GitHub Actions in the 3.9 test under the step
"Combine Linux and Windows coverage, uploiad to Coveralls"
there have been errors like this

```
Waiting for all jobs to start...
Got unknown status from AppVeyor API: starting
Failure.
Error: Process completed with exit code 1.
```

This came from the appveyor-artifacts script that was
last updated ten years ago, so this change adds a replacement
that recognizes the "starting" status