Fix "unsupported locale" in test
On Windows when running all tests locally, test_bytes_to_human()
failed like below. However, when running the test individually, it
was fine.

When test_invalid_locale() was called, it indirectly called
setup_translation() which set the locale, and getlocale()
returned ('en_US', 'ISO8859-1').

This tuple could not be passed to setlocale(). Also, it
could be passed as 'en_US.ISO8559-1', but 'en_US' worked.

======================================================================
ERROR: test_bytes_to_human (tests.TestFileUtilities.FileUtilitiesTestCase.test_bytes_to_human)
Unit test for class bytes_to_human
----------------------------------------------------------------------
Traceback (most recent call last):
  File "B:\tests\TestFileUtilities.py", line 211, in test_bytes_to_human
    locale.setlocale(locale.LC_NUMERIC, old_locale)
  File "c:\projects\vcpkg_installed\x86-windows\tools\python3\Lib\locale.py", line 627, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting