Improve warnings
* Treat warnings as errors.
* Prevent warnings.

Below is a warning that was fixed.

Exception ignored in: <sqlite3.Connection object at 0x7be91145ca90>
ResourceWarning: unclosed database in <sqlite3.Connection object at 0x7be91145ca90>

Below is an error, caused by a warning, that was fixed.

======================================================================
ERROR: test_preferences (tests.TestGUI.GUITestCase.test_preferences)
Opens the preferences dialog and closes it
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestGUI.py", line 179, in test_preferences
    pref = self.app.get_preferences_dialog()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 398, in get_preferences_dialog
    return self._window.get_preferences_dialog()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 881, in get_preferences_dialog
    return PreferencesDialog(
           ^^^^^^^^^^^^^^^^^^
  File "C:\projects\bleachbit\bleachbit\GuiPreferences.py", line 58, in __init__
    notebook.append_page(self.__general_page(),
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\bleachbit\bleachbit\GuiPreferences.py", line 296, in __general_page
    cb_win10_theme = Gtk.CheckButton(_("Windows 10 theme"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\bleachbit\vcpkg_installed\x86-windows\tools\python3\Lib\site-packages\gi\overrides\Gtk.py", line 1456, in __init__
    self._init(*args, **kwargs)
  File "C:\projects\bleachbit\vcpkg_installed\x86-windows\tools\python3\Lib\site-packages\gi\overrides\__init__.py", line 256, in new_init
    warnings.warn('Using positional arguments with the GObject constructor has been deprecated. '
gi.overrides.Gtk.PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/Projects/PyGObject/InitializerDeprecations