Add missing psutil
======================================================================
ERROR: tests.TestAction (unittest.loader._FailedTest.tests.TestAction)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.TestAction
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.11/x64/lib/python3.13/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.13.11/x64/lib/python3.13/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
    ~~~~~~~~~~^^^^^^
  File "/home/runner/work/bleachbit/bleachbit/tests/TestAction.py", line 48, in <module>
    from tests.TestFileUtilities import test_ini_helper
  File "/home/runner/work/bleachbit/bleachbit/tests/TestFileUtilities.py", line 28, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'