Ignore service control error 1052
Error: system.updates: Function: stop Windows service cryptsvc
Traceback (most recent call last):
File "bleachbit\Windows.pyc", line 318, in run_net_service_command
File "win32serviceutil.pyc", line 530, in StopServiceWithDeps
File "win32serviceutil.pyc", line 505, in __StopServiceWithTimeout
pywintypes.error: (1052, 'ControlService', 'The requested control is not
valid for this service.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "bleachbit\Worker.pyc", line 88, in execute
File "bleachbit\Command.pyc", line 166, in execute
File "bleachbit\Windows.pyc", line 251, in run_wu_service
File "bleachbit\Windows.pyc", line 324, in run_net_service_command
RuntimeError: Failed to stop service cryptsvc: (1052, 'ControlService',
'The requested control is not valid for this service.')
stop Windows service bits 0B

Reported first by M0RPHIUS
https://github.com/bleachbit/bleachbit/issues/1932
https://github.com/bleachbit/bleachbit/issues/1959
https://github.com/bleachbit/bleachbit/issues/1964