Inherit from BleachbitTestCase
Inherit to avoid an error in GitHub Actions caused by
conflict of bleachbit/Options.py doing shutdown

ValueError: I/O operation on closed file.
[...]
File "/home/runner/work/bleachbit/bleachbit/bleachbit/General.py",
line 203, in makedirs
    logger.debug('makedirs(%s)', path)
Message: 'makedirs(%s)'
Arguments: ('/home/runner/.config/bleachbit',)