Fix drag and drop on Wayland
When dragging on to the application on Ubuntu 26.04 with Wayland,
the target area showed a green highlight (which is okay).

However, when dropping, the console showed

(org.bleachbit.BleachBit:1928500): Gdk-WARNING **: 18:19:31.862:
../../../gdk/wayland/gdkselection-wayland.c:283: error reading selection
buffer: Operation was cancelled

Otherwise, the application did not otherwise react to dropping,
so DND was broken.