Split recycle bin test into per-drive and all-drives tests
- If the per-drive test fails, the all-drives test will continue
- Use subTest context manager for per-drive testing
- Add verification that recycle bin is empty after emptying all drives
- Tolerate specific failure under AppVeyor CI
  - All-drive empty recycle bin: works
  - Query contents per-drive: works
  - Verified that there are definately files in the recycle bin
  - Same test works locally but fails in AppVeyor
  - Test worked recently in AppVeyor but no clear cause related
    to our code or their server image
  - Per-drive emptying is not used outside the tests, so not
    a priority to maintain

test_empty_recycle_bin (tests.TestWindows.WindowsTestCase.test_empty_recycle_bin)
Unit test for empty_recycle_bin ... ok
test_empty_recycle_bin_all_drives_destructive (tests.TestWindows.WindowsTestCase.test_empty_recycle_bin_all_drives_destructive)
Empty recycle bin in all drives at once ... ok
test_empty_recycle_bin_per_drive_destructive (tests.TestWindows.WindowsTestCase.test_empty_recycle_bin_per_drive_destructive)
Empty recycle bin in each drive individually ... error in SHEmptyRecycleBin(): recycle_bin_size=786.4kB, num_files=25, path='C:\\'
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Windows.py", line 858, in empty_recycle_bin
    shell.SHEmptyRecycleBin(None, path, flags)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
  test_empty_recycle_bin_per_drive_destructive (tests.TestWindows.WindowsTestCase.test_empty_recycle_bin_per_drive_destructive) (drive='C:\\')
Empty recycle bin in each drive individually ... ERROR
test_file_wipe (tests.TestWindows.WindowsTestCase.test_file_wipe)
Unit test for file_wipe ... file_wipe(C:\Users\appveyor\AppData\Local\Temp\1\bleachbit-file-wiped7f9s6rx\short)