Pin py2exe version to 0.6.9 for Python 3.4 compatibility
%PYTHON_HOME%/Scripts/pip.exe install -r requirements.txt
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting pypiwin32==223 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Collecting winshell==0.6 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/91/3f/d23d248029a49042d278af9c86b53bc90845e3739a0d7493e00cbac0e4cd/winshell-0.6.zip
Collecting pefile==2019.4.18 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/36/58/acf7f35859d541985f0a6ea3c34baaefbfaee23642cf11e85fe36453ae77/pefile-2019.4.18.tar.gz (62kB)
Collecting py2exe (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/7d/2b/5bb512a67aaa465f8629f2c0d759f56b8136a973b355db32870beb5c76af/py2exe-0.10.0.2.tar.gz (104kB)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-azrr05tp\py2exe\setup.py", line 17, in <module>
        from py2exe.py2exe_distutils import Dist, Interpreter, BuildInterpreters
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-azrr05tp\py2exe\py2exe\__init__.py", line 9, in <module>
        patch_distutils()
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-azrr05tp\py2exe\py2exe\patch_distutils.py", line 68, in patch_distutils
        from . import distutils_buildexe
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-azrr05tp\py2exe\py2exe\distutils_buildexe.py", line 91, in <module>
        from . import runtime
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-azrr05tp\py2exe\py2exe\runtime.py", line 3, in <module>
        from .dllfinder import Scanner, pydll
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-azrr05tp\py2exe\py2exe\dllfinder.py", line 6, in <module>
        from . import pescan
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-install-azrr05tp\py2exe\py2exe\pescan.py", line 12, in <module>
        import pefile
    ImportError: No module named 'pefile'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in