Fix test_run_net_service_command
After updating the AppVeyor image from VS 2013 to VS 2022, the following
error started

======================================================================
ERROR: test_run_net_service_command
(tests.TestWindows.WindowsTestCase.test_run_net_service_command)
Integration test for run_net_service_command().
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\bleachbit\bleachbit\Windows.py", line 318, in
run_net_service_command
    action(service)
File
"C:\projects\bleachbit\vcpkg_installed\x86-windows\tools\python3\Lib\site-packages\win32\lib\win32serviceutil.py",
line 555, in StartService
    win32service.StartService(hs, args)
pywintypes.error: (1058, 'StartService', 'The service cannot be started,
either because it is disabled or because it has no enabled devices
associated with it.')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "C:\projects\bleachbit\tests\TestWindows.py", line 323, in
test_run_net_service_command
    run_net_service_command(service, True)
File "C:\projects\bleachbit\bleachbit\Windows.py", line 324, in
run_net_service_command
raise RuntimeError(f'Failed to {verb} service {service}: {e}') from
e
RuntimeError: Failed to start service spooler: (1058, 'StartService',
'The service cannot be started, either because it is disabled or because
it has no enabled devices associated with it.')