Allow fallback for language
Adding fallback=True eliminated the following error even when
the localedir was missing:

FileNotFoundError: [Errno 2] No translation file found for domain:
'message'"

This change also fixes these tests:

======================================================================
FAIL: test_encoding (tests.TestCLI.CLITestCase)
Unit test for encoding
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/bleachbit/bleachbit/tests/TestCLI.py", line
113, in test_encoding
    self._test_preview(args, redirect_stdout=False, env=env)
File "/home/travis/build/bleachbit/bleachbit/tests/TestCLI.py", line
60, in _test_preview
    self.assertEqual(pos, -1)
AssertionError: 319 != -1
======================================================================
FAIL: test_preview (tests.TestCLI.CLITestCase)
Unit test for --preview option
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/bleachbit/bleachbit/tests/TestCLI.py", line
152, in test_preview
    self._test_preview(args, env=env)
File "/home/travis/build/bleachbit/bleachbit/tests/TestCLI.py", line
60, in _test_preview
    self.assertEqual(pos, -1)
AssertionError: 319 != -1